baseurl = "https://vakhitov.dev/"
defaultcontentlanguage = "en-gb"
languagecode = "en-gb"
title = "Alex Vakhitov"

canonifyurls = true
paginate = 50

pygmentscodefences = true
[markup.goldmark.renderer]
unsafe = true

[permalinks]
posts = "/:year/:month/:title.html"

[params]
author = "Alex Vakhitov"
description = "Yet another blog about development and computers"
info = "Software Engineer and Haskeller"
keywords = "blog,developer,personal"

rtl = false

colorscheme = "light"
customCSS = ["css/syntax.css"]
hidecolorschemetoggle = true
math = true

[taxonomies]
author = "author"
category = "category"
series = "series"
tag = "tags"

# Social links
[[params.social]]
icon = "fa fa-github fa-2x"
name = "Github"
url = "https://github.com/vahaah/"
weight = 1
[[params.social]]
icon = "fa fa-twitter fa-2x"
name = "Twitter"
url = "https://twitter.com/vahaah/"
weight = 2
[[params.social]]
icon = "fa fa-rss"
name = "RSS"
rel = "alternate"
type = "application/rss+xml"
url = "https://vakhitov.dev/rss.xml"
weight = 6

[[menu.main]]
name = "About"
url = "/about/"
weight = 1
