name: Ruby

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@95193d6d4873cdecf7b7b51b30228f3e2d1b6aba
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
      - name: Test pages
        run: bundle exec rake clean && bundle exec rake pages
      - name: Test w3c
        run: bundle exec rake clean && bundle exec rake w3c
      - name: Test HTML proofer
        run: bundle exec rake clean && bundle exec rake proofer
      - name: Ping all foreign links
        run: bundle exec rake clean && bundle exec rake ping
      - name: Make sure all pages have excerpts
        run: bundle exec rake clean && bundle exec rake excerpts
      - name: Git Config
        run: git config --global user.email "alex.vakhitov@gmail.com" && git config --global user.name "Alex Vakhitov"
      - name: Deploy
        run: bundle exec jgd -u https://vahaah:${GITHUB_TOKEN}@github.com/vahaah/blog.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
